version: '3.8'

services:
  # 1. FRONTEND (Tu React App)
  frontend:
    build: .
    image: mi-frontend-gamer:v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # 2. BACKEND (Tu Spring Boot App)
  backend:
    # IMPORTANTE: Asegúrate de que esta ruta apunte a tu carpeta del backend
    build: ../levelup-gamer-backend
    image: levelup-backend:latest
    ports:
      - "8081:8081" # Exponemos el 8081 para que el Frontend pueda entrar
    environment:
      # Sobrescribimos la configuración de 'localhost' para usar los nombres de Docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/levelup_gamer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Coincide con la password de abajo
      - SPRING_RABBITMQ_HOST=rabbitmq    # Conecta con el servicio de abajo
    depends_on:
      - database
      - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # 3. BASE DE DATOS (MySQL)
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: levelup_db
    ports:
      - "3308:3306" # Opcional: Para ver la BD desde Workbench en tu PC
    volumes:
      - db_data:/var/lib/mysql # Guarda los datos aunque apagues Docker
    deploy:
      replicas: 1

  # 4. MENSAJERÍA (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto de mensajería (Backend -> RabbitMQ)
      - "15672:15672" # Panel visual (Tu Navegador -> RabbitMQ)
    deploy:
      replicas: 1

# Volúmenes para persistencia de datos
volumes:
  db_data: