version: '3.8'

services:
  # 1. FRONTEND (Tu React App)
  frontend:
    build: .
    image: mi-frontend-gamer:v1
    ports:
      - "3000:80"
    depends_on:
      - gateway  # El frontend ahora depende del Gateway, no directo del backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # 5. API GATEWAY (El nuevo Portero)
  gateway:
    build: ../levelup-gamer-gateway
    image: levelup-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # 2. BACKEND (Tu Spring Boot App)
  backend:
    build: ../levelup-gamer-backend
    image: levelup-backend:latest
    ports:
      - "8081:8081" # Lo dejamos expuesto por si necesitas debuggear, pero el tráfico real irá por el 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/levelup_gamer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - database
      - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # 3. BASE DE DATOS (MySQL)
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: levelup_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1

  # 4. MENSAJERÍA (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      replicas: 1

volumes:
  db_data: