name: CI/CD Pipeline LevelUp Gamer

on:
  push:
    branches: [ "main" ]  # Se activa cuando subes cambios a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    # 1. Descarga tu código
    - name: Checkout del código
      uses: actions/checkout@v3
    
    # 2. Se conecta a Docker Hub
    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
    # 3. Construye y sube la imagen
    - name: Construir y Subir Imagen Frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: valdasy/levelup-frontend:latest